### ISSUE TITLE
Notebook release

### ISSUE THREAD

**Issue by thaume** [bayesimpact/readmission-risk#1]
Hello there !

Great repo, it was great to go through it. I'm now wondering if you will release the python notebook :) Thanks !

**Comment by thaume** [comment]
@AlexNisnevich  I'm just doing one ping then I'm done :)

**Comment by AlexNisnevich** [comment]
@mjamei Would it be possible to release the `statistics.ipynb` notebook? I can't remember if there was anything sensitive in it.

**Comment by mjamei** [comment]
@AlexNisnevich I am not able to find it in the repo. Any idea where it could be?

**Comment by AlexNisnevich** [comment]
I think it's in the `notebooks` directory of the private repo.

**Comment by thaume** [comment]
@AlexNisnevich @mjamei thanks !

**Comment by thaume** [comment]
@mjamei  @AlexNisnevich thanks guys ! Have a nice day
